language: node_js
node_js: stable

# S: Build Lifecycle
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli

install:
  - npm install
  
before_script:
  - npm install -g gulp

script:
  - git submodule init #用于更新主题, 更新源为自己的主题项目，否则会 clone 最新 NexT 主题，而官方主题配置文件没有设置
  - git submodule update
  - hexo clean && hexo g
  - gulp default #使用 gulp 对流程进行优化

 after_script:
  - cd ./public
  - git init
  - git config user.name "cyang812"
  - git config user.email "cy950812@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: git@github.com:cyang812/cyang812.github.io.git
   #设置 GH_REF，注意更改 yourname